/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CodeRouteImport } from './routes/code'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as VentureRouteImport } from './routes/venture'
import { Route as WorldRouteImport } from './routes/world'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AiPlaygroundIdRouteImport } from './routes/ai.$playgroundId'
import { Route as BossBossIdRouteImport } from './routes/boss.$bossId'
import { Route as CodeIndexRouteImport } from './routes/code.index'
import { Route as CodeLabIdRouteImport } from './routes/code.$labId'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateStudioIdRouteImport } from './routes/create.$studioId'
import { Route as EnglishIndexRouteImport } from './routes/english.index'
import { Route as EnglishVenueIdRouteImport } from './routes/english.$venueId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnDomainIdRouteImport } from './routes/learn.$domainId'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as MissionsMissionIdRouteImport } from './routes/missions.$missionId'
import { Route as VentureIndexRouteImport } from './routes/venture.index'
import { Route as VentureLabIdRouteImport } from './routes/venture.$labId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const VentureRoute = VentureRouteImport.update({
  id: '/venture',
  path: '/venture',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const AiPlaygroundIdRoute = AiPlaygroundIdRouteImport.update({
  id: '/$playgroundId',
  path: '/$playgroundId',
  getParentRoute: () => AiRoute,
} as any)
const BossBossIdRoute = BossBossIdRouteImport.update({
  id: '/boss/$bossId',
  path: '/boss/$bossId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeIndexRoute = CodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodeRoute,
} as any)
const CodeLabIdRoute = CodeLabIdRouteImport.update({
  id: '/$labId',
  path: '/$labId',
  getParentRoute: () => CodeRoute,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const CreateStudioIdRoute = CreateStudioIdRouteImport.update({
  id: '/$studioId',
  path: '/$studioId',
  getParentRoute: () => CreateRoute,
} as any)
const EnglishIndexRoute = EnglishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishVenueIdRoute = EnglishVenueIdRouteImport.update({
  id: '/$venueId',
  path: '/$venueId',
  getParentRoute: () => EnglishRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnDomainIdRoute = LearnDomainIdRouteImport.update({
  id: '/learn/$domainId',
  path: '/learn/$domainId',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdRoute = MissionsMissionIdRouteImport.update({
  id: '/missions/$missionId',
  path: '/missions/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const VentureIndexRoute = VentureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VentureRoute,
} as any)
const VentureLabIdRoute = VentureLabIdRouteImport.update({
  id: '/$labId',
  path: '/$labId',
  getParentRoute: () => VentureRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/characters': typeof CharactersRoute
  '/code': typeof CodeRouteWithChildren
  '/community': typeof CommunityRoute
  '/create': typeof CreateRouteWithChildren
  '/curriculum': typeof CurriculumRoute
  '/design-system': typeof DesignSystemRoute
  '/english': typeof EnglishRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/portfolio': typeof PortfolioRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/safety': typeof SafetyRoute
  '/simulations': typeof SimulationsRoute
  '/stories': typeof StoriesRoute
  '/venture': typeof VentureRouteWithChildren
  '/world': typeof WorldRoute
  '/ai/$playgroundId': typeof AiPlaygroundIdRoute
  '/boss/$bossId': typeof BossBossIdRoute
  '/code/$labId': typeof CodeLabIdRoute
  '/create/$studioId': typeof CreateStudioIdRoute
  '/english/$venueId': typeof EnglishVenueIdRoute
  '/learn/$domainId': typeof LearnDomainIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/venture/$labId': typeof VentureLabIdRoute
  '/ai/': typeof AiIndexRoute
  '/code/': typeof CodeIndexRoute
  '/create/': typeof CreateIndexRoute
  '/english/': typeof EnglishIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/venture/': typeof VentureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/challenges': typeof ChallengesRoute
  '/characters': typeof CharactersRoute
  '/community': typeof CommunityRoute
  '/curriculum': typeof CurriculumRoute
  '/design-system': typeof DesignSystemRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/portfolio': typeof PortfolioRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/safety': typeof SafetyRoute
  '/simulations': typeof SimulationsRoute
  '/stories': typeof StoriesRoute
  '/world': typeof WorldRoute
  '/ai/$playgroundId': typeof AiPlaygroundIdRoute
  '/boss/$bossId': typeof BossBossIdRoute
  '/code/$labId': typeof CodeLabIdRoute
  '/create/$studioId': typeof CreateStudioIdRoute
  '/english/$venueId': typeof EnglishVenueIdRoute
  '/learn/$domainId': typeof LearnDomainIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/venture/$labId': typeof VentureLabIdRoute
  '/ai': typeof AiIndexRoute
  '/code': typeof CodeIndexRoute
  '/create': typeof CreateIndexRoute
  '/english': typeof EnglishIndexRoute
  '/learn': typeof LearnIndexRoute
  '/missions': typeof MissionsIndexRoute
  '/venture': typeof VentureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/characters': typeof CharactersRoute
  '/code': typeof CodeRouteWithChildren
  '/community': typeof CommunityRoute
  '/create': typeof CreateRouteWithChildren
  '/curriculum': typeof CurriculumRoute
  '/design-system': typeof DesignSystemRoute
  '/english': typeof EnglishRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/portfolio': typeof PortfolioRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/safety': typeof SafetyRoute
  '/simulations': typeof SimulationsRoute
  '/stories': typeof StoriesRoute
  '/venture': typeof VentureRouteWithChildren
  '/world': typeof WorldRoute
  '/ai/$playgroundId': typeof AiPlaygroundIdRoute
  '/boss/$bossId': typeof BossBossIdRoute
  '/code/$labId': typeof CodeLabIdRoute
  '/create/$studioId': typeof CreateStudioIdRoute
  '/english/$venueId': typeof EnglishVenueIdRoute
  '/learn/$domainId': typeof LearnDomainIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/venture/$labId': typeof VentureLabIdRoute
  '/ai/': typeof AiIndexRoute
  '/code/': typeof CodeIndexRoute
  '/create/': typeof CreateIndexRoute
  '/english/': typeof EnglishIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/venture/': typeof VentureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/ai'
    | '/challenges'
    | '/characters'
    | '/code'
    | '/community'
    | '/create'
    | '/curriculum'
    | '/design-system'
    | '/english'
    | '/onboarding'
    | '/parents'
    | '/portfolio'
    | '/practice'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/safety'
    | '/simulations'
    | '/stories'
    | '/venture'
    | '/world'
    | '/ai/$playgroundId'
    | '/boss/$bossId'
    | '/code/$labId'
    | '/create/$studioId'
    | '/english/$venueId'
    | '/learn/$domainId'
    | '/missions/$missionId'
    | '/venture/$labId'
    | '/ai/'
    | '/code/'
    | '/create/'
    | '/english/'
    | '/learn/'
    | '/missions/'
    | '/venture/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/challenges'
    | '/characters'
    | '/community'
    | '/curriculum'
    | '/design-system'
    | '/onboarding'
    | '/parents'
    | '/portfolio'
    | '/practice'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/safety'
    | '/simulations'
    | '/stories'
    | '/world'
    | '/ai/$playgroundId'
    | '/boss/$bossId'
    | '/code/$labId'
    | '/create/$studioId'
    | '/english/$venueId'
    | '/learn/$domainId'
    | '/missions/$missionId'
    | '/venture/$labId'
    | '/ai'
    | '/code'
    | '/create'
    | '/english'
    | '/learn'
    | '/missions'
    | '/venture'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/ai'
    | '/challenges'
    | '/characters'
    | '/code'
    | '/community'
    | '/create'
    | '/curriculum'
    | '/design-system'
    | '/english'
    | '/onboarding'
    | '/parents'
    | '/portfolio'
    | '/practice'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/safety'
    | '/simulations'
    | '/stories'
    | '/venture'
    | '/world'
    | '/ai/$playgroundId'
    | '/boss/$bossId'
    | '/code/$labId'
    | '/create/$studioId'
    | '/english/$venueId'
    | '/learn/$domainId'
    | '/missions/$missionId'
    | '/venture/$labId'
    | '/ai/'
    | '/code/'
    | '/create/'
    | '/english/'
    | '/learn/'
    | '/missions/'
    | '/venture/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AiRoute: typeof AiRouteWithChildren
  ChallengesRoute: typeof ChallengesRoute
  CharactersRoute: typeof CharactersRoute
  CodeRoute: typeof CodeRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  CreateRoute: typeof CreateRouteWithChildren
  CurriculumRoute: typeof CurriculumRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EnglishRoute: typeof EnglishRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ParentsRoute: typeof ParentsRoute
  PortfolioRoute: typeof PortfolioRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ProjectsRoute: typeof ProjectsRoute
  SafetyRoute: typeof SafetyRoute
  SimulationsRoute: typeof SimulationsRoute
  StoriesRoute: typeof StoriesRoute
  VentureRoute: typeof VentureRouteWithChildren
  WorldRoute: typeof WorldRoute
  BossBossIdRoute: typeof BossBossIdRoute
  LearnDomainIdRoute: typeof LearnDomainIdRoute
  MissionsMissionIdRoute: typeof MissionsMissionIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venture': {
      id: '/venture'
      path: '/venture'
      fullPath: '/venture'
      preLoaderRoute: typeof VentureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/$playgroundId': {
      id: '/ai/$playgroundId'
      path: '/$playgroundId'
      fullPath: '/ai/$playgroundId'
      preLoaderRoute: typeof AiPlaygroundIdRouteImport
      parentRoute: typeof AiRoute
    }
    '/boss/$bossId': {
      id: '/boss/$bossId'
      path: '/boss/$bossId'
      fullPath: '/boss/$bossId'
      preLoaderRoute: typeof BossBossIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/': {
      id: '/code/'
      path: '/'
      fullPath: '/code/'
      preLoaderRoute: typeof CodeIndexRouteImport
      parentRoute: typeof CodeRoute
    }
    '/code/$labId': {
      id: '/code/$labId'
      path: '/$labId'
      fullPath: '/code/$labId'
      preLoaderRoute: typeof CodeLabIdRouteImport
      parentRoute: typeof CodeRoute
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/$studioId': {
      id: '/create/$studioId'
      path: '/$studioId'
      fullPath: '/create/$studioId'
      preLoaderRoute: typeof CreateStudioIdRouteImport
      parentRoute: typeof CreateRoute
    }
    '/english/': {
      id: '/english/'
      path: '/'
      fullPath: '/english/'
      preLoaderRoute: typeof EnglishIndexRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/$venueId': {
      id: '/english/$venueId'
      path: '/$venueId'
      fullPath: '/english/$venueId'
      preLoaderRoute: typeof EnglishVenueIdRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$domainId': {
      id: '/learn/$domainId'
      path: '/learn/$domainId'
      fullPath: '/learn/$domainId'
      preLoaderRoute: typeof LearnDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId': {
      id: '/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof MissionsMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venture/': {
      id: '/venture/'
      path: '/'
      fullPath: '/venture/'
      preLoaderRoute: typeof VentureIndexRouteImport
      parentRoute: typeof VentureRoute
    }
    '/venture/$labId': {
      id: '/venture/$labId'
      path: '/$labId'
      fullPath: '/venture/$labId'
      preLoaderRoute: typeof VentureLabIdRouteImport
      parentRoute: typeof VentureRoute
    }
  }
}

interface AiRouteChildren {
  AiPlaygroundIdRoute: typeof AiPlaygroundIdRoute
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiPlaygroundIdRoute: AiPlaygroundIdRoute,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface CodeRouteChildren {
  CodeLabIdRoute: typeof CodeLabIdRoute
  CodeIndexRoute: typeof CodeIndexRoute
}

const CodeRouteChildren: CodeRouteChildren = {
  CodeLabIdRoute: CodeLabIdRoute,
  CodeIndexRoute: CodeIndexRoute,
}

const CodeRouteWithChildren = CodeRoute._addFileChildren(CodeRouteChildren)

interface CreateRouteChildren {
  CreateStudioIdRoute: typeof CreateStudioIdRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateStudioIdRoute: CreateStudioIdRoute,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

interface EnglishRouteChildren {
  EnglishVenueIdRoute: typeof EnglishVenueIdRoute
  EnglishIndexRoute: typeof EnglishIndexRoute
}

const EnglishRouteChildren: EnglishRouteChildren = {
  EnglishVenueIdRoute: EnglishVenueIdRoute,
  EnglishIndexRoute: EnglishIndexRoute,
}

const EnglishRouteWithChildren =
  EnglishRoute._addFileChildren(EnglishRouteChildren)

interface VentureRouteChildren {
  VentureLabIdRoute: typeof VentureLabIdRoute
  VentureIndexRoute: typeof VentureIndexRoute
}

const VentureRouteChildren: VentureRouteChildren = {
  VentureLabIdRoute: VentureLabIdRoute,
  VentureIndexRoute: VentureIndexRoute,
}

const VentureRouteWithChildren =
  VentureRoute._addFileChildren(VentureRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AiRoute: AiRouteWithChildren,
  ChallengesRoute: ChallengesRoute,
  CharactersRoute: CharactersRoute,
  CodeRoute: CodeRouteWithChildren,
  CommunityRoute: CommunityRoute,
  CreateRoute: CreateRouteWithChildren,
  CurriculumRoute: CurriculumRoute,
  DesignSystemRoute: DesignSystemRoute,
  EnglishRoute: EnglishRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ParentsRoute: ParentsRoute,
  PortfolioRoute: PortfolioRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ProjectsRoute: ProjectsRoute,
  SafetyRoute: SafetyRoute,
  SimulationsRoute: SimulationsRoute,
  StoriesRoute: StoriesRoute,
  VentureRoute: VentureRouteWithChildren,
  WorldRoute: WorldRoute,
  BossBossIdRoute: BossBossIdRoute,
  LearnDomainIdRoute: LearnDomainIdRoute,
  MissionsMissionIdRoute: MissionsMissionIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
